# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/news_service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'proto/news_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18proto/news_service.proto\x12\x04news\"0\n\x0eGetNewsRequest\x12\x10\n\x08\x63\x61tegory\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\"\x1f\n\x11GetOneNewsRequest\x12\n\n\x02id\x18\x01 \x01(\t\"/\n\x0fGetNewsResponse\x12\x1c\n\x04news\x18\x01 \x03(\x0b\x32\x0e.news.NewsItem\" \n\x11ScrapeNewsRequest\x12\x0b\n\x03url\x18\x01 \x01(\t\"%\n\x12ScrapeNewsResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"j\n\x08NewsItem\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x03 \x01(\t\x12\x11\n\tpublisher\x18\x04 \x01(\t\x12\x0b\n\x03url\x18\x05 \x01(\t\x12\x10\n\x08\x65vent_id\x18\x06 \x01(\t\"N\n\x11UpdateNewsRequest\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x03 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x04 \x01(\t\"6\n\x12UpdateNewsResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\" \n\x11\x44\x65leteNewsRequest\x12\x0b\n\x03url\x18\x01 \x01(\t\"6\n\x12\x44\x65leteNewsResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xce\x02\n\x0bNewsService\x12\x41\n\nScrapeNews\x12\x17.news.ScrapeNewsRequest\x1a\x18.news.ScrapeNewsResponse\"\x00\x12\x38\n\x07GetNews\x12\x14.news.GetNewsRequest\x1a\x15.news.GetNewsResponse\"\x00\x12<\n\nGetOneNews\x12\x17.news.GetOneNewsRequest\x1a\x15.news.GetNewsResponse\x12\x41\n\nUpdateNews\x12\x17.news.UpdateNewsRequest\x1a\x18.news.UpdateNewsResponse\"\x00\x12\x41\n\nDeleteNews\x12\x17.news.DeleteNewsRequest\x1a\x18.news.DeleteNewsResponse\"\x00\x42\x30Z.github.com/yourusername/gateway/internal/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.news_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z.github.com/yourusername/gateway/internal/proto'
  _globals['_GETNEWSREQUEST']._serialized_start=34
  _globals['_GETNEWSREQUEST']._serialized_end=82
  _globals['_GETONENEWSREQUEST']._serialized_start=84
  _globals['_GETONENEWSREQUEST']._serialized_end=115
  _globals['_GETNEWSRESPONSE']._serialized_start=117
  _globals['_GETNEWSRESPONSE']._serialized_end=164
  _globals['_SCRAPENEWSREQUEST']._serialized_start=166
  _globals['_SCRAPENEWSREQUEST']._serialized_end=198
  _globals['_SCRAPENEWSRESPONSE']._serialized_start=200
  _globals['_SCRAPENEWSRESPONSE']._serialized_end=237
  _globals['_NEWSITEM']._serialized_start=239
  _globals['_NEWSITEM']._serialized_end=345
  _globals['_UPDATENEWSREQUEST']._serialized_start=347
  _globals['_UPDATENEWSREQUEST']._serialized_end=425
  _globals['_UPDATENEWSRESPONSE']._serialized_start=427
  _globals['_UPDATENEWSRESPONSE']._serialized_end=481
  _globals['_DELETENEWSREQUEST']._serialized_start=483
  _globals['_DELETENEWSREQUEST']._serialized_end=515
  _globals['_DELETENEWSRESPONSE']._serialized_start=517
  _globals['_DELETENEWSRESPONSE']._serialized_end=571
  _globals['_NEWSSERVICE']._serialized_start=574
  _globals['_NEWSSERVICE']._serialized_end=908
# @@protoc_insertion_point(module_scope)
